### ISSUE TITLE
[feat]: Create folder for graph-algorithms

### ISSUE THREAD

**Issue by FischkopDev** [avantikachauhann/Algorithm-Alchemy#47]
Create a folder for graph-algorithms like Dijkstra, DFS,... 
It should contain one datastructure representation of graphs like adjacencyfields for a standard ussage in future graph-algorithms

**Comment by avantikachauhann** [comment]
You can go ahead with the proposed changes if you like.

**Comment by FischkopDev** [comment]
ok I'll work on it

**Comment by avantikachauhann** [comment]
Solved by #55
