### ISSUE TITLE
Palindrome Permutation in Java in Strings

### ISSUE THREAD

**Issue by avantikachauhann** [avantikachauhann/Algorithm-Alchemy#58]
This function would check if a string is a permutation of a palindrome in linear time.

**Comment by mownika-senthamilselvan** [comment]
Hey there, like to work on this issue , assign it me.

**Comment by JohnWickFirst** [comment]
> This function would check if a string is a permutation of a palindrome in linear time.

Is this issue still open then i would like to work on this.

**Comment by JohnWickFirst** [comment]
Created the PR. Please review and suggest/merge.
