### ISSUE TITLE
Patterns in python and java

### ISSUE THREAD

**Issue by kom-senapati** [avantikachauhann/Algorithm-Alchemy#70]
### I want to add the following 3 patterns in Python and Java to your repository.
1. Hollow Diamond
    - ![image](https://github.com/avantikachauhann/Algorithm-Alchemy/assets/92045934/6aa97598-ed84-41a6-8be2-32193a2d8270)

1. Floyd's Triangle Pattern
    - ![image](https://github.com/avantikachauhann/Algorithm-Alchemy/assets/92045934/54c2c6ed-9531-4603-b911-5a1bb28fb16a)

1. Pascal Triangle Pattern
    - ![image](https://github.com/avantikachauhann/Algorithm-Alchemy/assets/92045934/509774f6-459f-49dd-afcf-f3061ee68f7d)

**Comment by avantikachauhann** [comment]
okay, go ahead! assigning it to you!
